import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#785600',
        'primary-container': '#986d00',
        'primary-fixed': '#ffdea6',
        'primary-fixed-dim': '#f7bd48',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#271900',
        'on-primary-fixed-variant': '#5d4200',
        'secondary': '#5f5e5e',
        'secondary-container': '#e4e2e1',
        'secondary-fixed': '#e4e2e1',
        'secondary-fixed-dim': '#c8c6c6',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#656464',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474747',
        'tertiary': '#085ea2',
        'tertiary-container': '#3477bc',
        'tertiary-fixed': '#d2e4ff',
        'tertiary-fixed-dim': '#a1c9ff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fdfcff',
        'on-tertiary-fixed': '#001c37',
        'on-tertiary-fixed-variant': '#004880',
        'background': '#fbf9f6',
        'surface': '#fbf9f6',
        'surface-bright': '#fbf9f6',
        'surface-dim': '#dbdad7',
        'surface-variant': '#e4e2df',
        'surface-tint': '#7b5800',
        'surface-container': '#efeeeb',
        'surface-container-low': '#f5f3f0',
        'surface-container-high': '#eae8e5',
        'surface-container-highest': '#e4e2df',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#4f4535',
        'on-background': '#1b1c1a',
        'inverse-surface': '#30312f',
        'inverse-on-surface': '#f2f0ed',
        'inverse-primary': '#f7bd48',
        'outline': '#817563',
        'outline-variant': '#d3c4af',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        'headline': ['"Noto Serif"', 'Georgia', 'serif'],
        'body': ['Manrope', 'system-ui', 'sans-serif'],
        'label': ['Manrope', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      animation: {
        'fade-up': 'fadeUp 0.6s ease-out forwards',
        'fade-in': 'fadeIn 0.8s ease-out forwards',
        'slide-in-right': 'slideInRight 0.6s ease-out forwards',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [],
}
export default config
